### ISSUE TITLE
Wrong description of `typeof` in README

### ISSUE THREAD

**Issue by maxnordlund** [Gillespie59/eslint-plugin-angular#100]
Don't confuse `typeof`operator with `Object.prototype.toString.call`, the examples in the README are for the latter, not the former.

Value      | `typeof`       | `Object.prototype.toString.call`
------------|----------------|---------------------------------
`[]`        | `"object"`     | `"[object Array]"`
`{}`        | `"object"`     | `"[object Object]"`
`null`      | `"object"`     | `"[object Null]"`
`undefined` | `"undefined"`  | `"[object Undefined]"`
`NaN`       | `"number"`     | `"[object Number]"`
`0`         | `"number"`     | `"[object Number]"`
`false`     | `"boolean"`    | `"[object Boolean]"`
`""`        | `"string"`     | `"[object String]"`

**Comment by Gillespie59** [comment]
Thanks @maxnordlund 
Changes commited
