### ISSUE TITLE
Enforce deferring controller logic

### ISSUE THREAD

**Issue by alecxe** [Gillespie59/eslint-plugin-angular#104]
Several month ago we started to follow the John Papa's styleguide and enforce some of the guidelines via custom ESLint rules. One of the rules we've implemented was to enforce deferring the logic implemented in controller to factories and services.

Here is the related SO thread containing the custom rule we've implemented: [Enforce deferring controller logic](http://stackoverflow.com/questions/27806800/enforce-deferring-controller-logic).

Does it make sense to make this rule a part of `eslint-plugin-angular`? Apologies, if there is a rule like this, or this is a duplicate issue.

Thank you!

**Comment by Gillespie59** [comment]
Hi @alecxe 

What if the difference with the rule we already have : ng_no_services ? 

Manu

**Comment by alecxe** [comment]
@Gillespie59 great! `ng_no_services` covers even more than the mentioned custom rule. Closing. Many thanks!
