### ISSUE TITLE
rules/ng_function_type.js callee.property.name undefined

### ISSUE THREAD

**Issue by loganom** [Gillespie59/eslint-plugin-angular#105]
TypeError: Cannot read property 'name' of undefined

eslint-plugin-angular/rules/ng_no_services.js
Line 54

What information would be useful to help troubleshoot this issue?
npm --version 2.7.4

Issue found while running `npm start` after version 0.0.8 released. Our package.json had the eslint-plugin-angular dependency of `latest`. Reverting to 0.0.7 is a temporary fix.

**Comment by Gillespie59** [comment]
Hi @loganom 

I need the snippet of code that is the source of this problem ? Can you share the file with this problem ? 

Manu

**Comment by loganom** [comment]
issue found when running npm install

**Comment by loganom** [comment]
@Gillespie59 updated original comment.

**Comment by Gillespie59** [comment]
you have this error  when doing a `npm install` ? strange. This eror is similar to a "runtime" error. You should have this kind of error when executing the linter to your source code.

**Comment by Gillespie59** [comment]
I have just pushed a fix. Can you give a try to the code hosted on the 0.0.9 branch ?

**Comment by loganom** [comment]
Yes, that works for me. +1
Thanks!

**Comment by mattlewis92** [comment]
That worked for me as well. However the `angular/ng_module_getter` doesn't seem to work. It says:
`Avoid using a variable and instead use chaining with the getter syntax`

With the following code:
```
'use strict';

angular.module('mwl.calendar', []);
```

It gives this error for all my source files.

**Comment by loganom** [comment]
I just noticed that as well actually. @Gillespie59 Should this be a new issue?, I think you've resolved this one.

**Comment by Gillespie59** [comment]
I close this issue. And we continue to discuss about the second one of this thread #103

**Comment by mastertinner** [comment]
I'm stillgetting this issue...

```javascript
var cleanUp;

cleanUp = $rootScope.$on('$stateChangeSuccess', function () {
  vm.currentHor = $state.$current.path[0].self.name;
});
  
$scope.$on('$destroy', function () {
  cleanUp();
});
```

using 0.2.2

And the output is:
```
/usr/local/lib/node_modules/eslint-plugin-angular/rules/ng_function_type.js:36
                angularObjectName = callee.property.name,
                                                   ^
TypeError: Cannot read property 'name' of undefined
    at EventEmitter.CallExpression (/usr/local/lib/node_modules/eslint-plugin-angular/rules/ng_function_type.js:36:52)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/usr/local/lib/node_modules/eslint/lib/eslint.js:794:25)
    at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:787:24)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:199:27)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:224:12)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:320:26
    at walk (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:82:9)
```

When removing the line ```cleanUp();``` there is no more error.

**Comment by Gillespie59** [comment]
hi @mastertinner 

I have pushed a fix for this issue, available on the 0.2.3 release

Thanks

**Comment by mastertinner** [comment]
That fixed my problem. Thanks so much for the quick reply @Gillespie59 !

**Comment by Gillespie59** [comment]
You're welcome ;)
