### ISSUE TITLE
Release more often (can I help make that happen?)

### ISSUE THREAD

**Issue by davidmason** [Gillespie59/eslint-plugin-angular#108]
I am being hit by a bug in the latest release that is fixed in the 0.0.9 branch. I ran `git diff master 0.0.9` and it looks like you have several bug-fixes saved up that have not been released yet.

@Gillespie59 Is there anything I can do to help get the next release out?

Would you be open to discussing the approach to versioning and releases for this project?

**Comment by Gillespie59** [comment]
I did not have any approach for versioning for this moment right now. 
Before the 0.0.9 release I would like to solve #103 #106 and #107 
You can take one of these issues i you want.

**Comment by dustinspecker** [comment]
If you want to take advantage of unreleased commits, you can install modules directly from GitHub and specify a branch or commit.

`npm install --save-dev gillespie59/eslint-plugin-angular#0.0.9`
or
`npm install --save-dev gillespie59/eslint-plugin-angular#f847851ce2336046d1bc11486c28ee05ae8acec3`

**Comment by davidmason** [comment]
> I did not have any approach for versioning for this moment right now.

My suggestion is to do a release every time a bug is fixed or a rule is added, using semver for version numbers. That would allow npm users to benefit from that code straight away (especially the bug fixes).

Using the semver structure [breaking].[feature].[bugfix], someone can easily specify version ranges or use '^' or '~' in front of their version in package.json so that they can choose whether they want to automatically get new features (rules) or just bugfixes.

I would also suggest moving the version up to 1.0.0 because the ^ operator (the default for `npm install --save`) behaves differently on 0.x.x compared to [>0].x.x (see [npm - semver - caret-ranges](https://docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4)). Versions >= 1.0.0 will give the behaviour people expect.

**Comment by davidmason** [comment]
> Before the 0.0.9 release I would like to solve #103 #106 and #107
> You can take one of these issues i you want.

Looks like #106 is fixed, and you are working on #103, so I will see if I can figure out #107.

**Comment by davidmason** [comment]
@dustinspecker I like to avoid that whenever I can, since it circumvents the use of semver to control what type of changes I automatically accept. It is a handy fallback when there is no other option though.

**Comment by Gillespie59** [comment]
Yes you are right. the #106 is fixed. 

And I am OK with your idea about versionning. 

So when the #103 or #107 are fixed, we will create a 0.0.9 and 0.0.10 release ? 

And done, after each rule will update the second digit after each new rule ? 0.1.0 ... ? 

Thanks for the proposition

**Comment by davidmason** [comment]
> So when the #103 or #107 are fixed, we will create a 0.0.9 and 0.0.10 release ?
> And done, after each rule will update the second digit after each new rule ? 0.1.0 ... ? 

That sounds right, although I would also suggest moving to 1.0.0 as soon as possible, then increment the feature and bugfix versions from there. Semver is a bit inconsistent for 0.x.x compared to other versions, so the default version setting in package.json from `npm install --save-dev eslint-plugin-angular` will not automatically pick up any bugfix or new-feature releases until the version is 1.0.0 or higher.

**Comment by davidmason** [comment]
> Before the 0.0.9 release I would like to solve #103 #106 and #107

I submitted a pull request that I think will solve #107 (see #111). Let me know if there is any problem with the coding style or the behaviour and I can update it.

**Comment by Gillespie59** [comment]
for testing the coding style, you can run gulp quality (i think ;)). and add some unit tests

But of course I will have a look to your PR

**Comment by davidmason** [comment]
> for testing the coding style, you can run gulp quality (i think ;)). and add some unit tests

Already done :)

**Comment by Gillespie59** [comment]
0.0.9 released. 
Thanks
