### ISSUE TITLE
Remove eslint from peerDependencies

### ISSUE THREAD

**Issue by davidmason** [Gillespie59/eslint-plugin-angular#110]
npm peerDependencies are a bit of a mess at the moment: https://github.com/npm/npm/issues/5080

I am using `gulp-eslint` to run eslint, so I end up with 2 copies of eslint in my node_modules, and the one that is installed because of this peer dependency is not the one that is used to run the plugin. This means that in my case there is no guarantee provided by the peer dependency that the plugin will run with a compatible version of eslint.

I would expect a large proportion of projects to be running eslint through a task runner, so I expect that this situation is pretty common. Until peer dependencies are fixed, it may be better just to document the required eslint version in the readme and not include the peer dependency. Does that sound sensible?

**Comment by Gillespie59** [comment]
I agree. And in fact each we execute the NG plugin, we have warning message due to peerDependencies. 

So we can remove this property. And add a paragraph in the README.md about the the different version of ESLint we support.

**Comment by davidmason** [comment]
This change might be a good opportunity to increase the version to 1.0.0, since it is technically a breaking change. If someone has specified `eslint-plugin-angular` as a dependency but has not specified `eslint`, then has a script that uses `eslint`, their script would stop working.

**Comment by albertosantini** [comment]
I report this as memo. :)

Installed eslint `1.0.0-rc-1`

```
...
npm ERR! peerinvalid The package eslint does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-angular@0.0.15 wants eslint@>=0.8.0
...
```

However eslint `1.0.0-rc-1` is installed in spite of the npm error.

**Comment by Delagen** [comment]
+1

**Comment by Gillespie59** [comment]
I will let you try the migration-1.1.0 branch  where I fixed this issue. If everything is OK I will create the 0.5.0 release

**Comment by albertosantini** [comment]
I had the opportunity only now to test `0.6.0`.
It is ok.

**Comment by Gillespie59** [comment]
Thanks @albertosantini
