### ISSUE TITLE
2 rules with same name : "ng_on_watch"

### ISSUE THREAD

**Issue by fabm22** [Gillespie59/eslint-plugin-angular#112]
There is two times the rule "ng_on_watch" on the list of rules here in the docs.

**Comment by davidmason** [comment]
@fabm22 it looks like this is fixed in branch 0.0.9, which I think is quite close to release.

**Comment by Gillespie59** [comment]
I am waiting for a last feedback about my fix. And will do the release.

**Comment by Gillespie59** [comment]
This pb is due to a PR done on the master branch. Did not check before merging. Asked the commiter to do it again on the right branch.

**Comment by fabm22** [comment]
Thanks a lot for feedback

**Comment by Gillespie59** [comment]
0.0.9 released. 
Thanks
