### ISSUE TITLE
Configuration is wrong

### ISSUE THREAD

**Issue by mato75** [Gillespie59/eslint-plugin-angular#116]
Configuration for rule "no-underscore-dangle" is invalid:
	Value "false" is the wrong type.

**Comment by Delagen** [comment]
It's eslint error in 0.23 i think. So instead of false use 0.

**Comment by Gillespie59** [comment]
Hi

We do not have any no-underscore-dangle rule in this plugin. 

Manu

**Comment by Gillespie59** [comment]
I closed this issue because this is nt an issue of the NG plugin. 
We can open it back if needed.
