### ISSUE TITLE
'ng_no_service_method' rule points to wrong John Papa's Angular styleguide recommendation (it seems)

### ISSUE THREAD

**Issue by fabm22** [Gillespie59/eslint-plugin-angular#122]
It seems the rule points to wrong style recommendation. I might be wrong but I think it should point to y40 instead. See :

(is)  https://github.com/johnpapa/angular-styleguide#style-y181

VS

(should be) https://github.com/johnpapa/angular-styleguide#style-y040

**Comment by Gillespie59** [comment]
Thanks @fabm22
