### ISSUE TITLE
angular.isBoolean does not exist, remove ng_typecheck_boolean

### ISSUE THREAD

**Issue by keirlawson** [Gillespie59/eslint-plugin-angular#123]
This rule is enabled by default yet no angular.isBoolean function exists. It should be removed.

**Comment by Gillespie59** [comment]
You are right. I do not know I have created this rule ;)
Thanks

**Comment by Gillespie59** [comment]
Problem solved. and 0.0.13 published on NPM. 

Thanks.

**Comment by tilmanpotthof** [comment]
Rule is still existent in the code.
