### ISSUE TITLE
Please support eslint 1.1.0

### ISSUE THREAD

**Issue by mastertinner** [Gillespie59/eslint-plugin-angular#155]

**Comment by Delagen** [comment]
+1

**Comment by AdriVanHoudt** [comment]
:+1:

**Comment by Gillespie59** [comment]
the migration is on progress, on a specific branch.
Still few things to do 
- Define the schema for all rules
- Review Demos

**Comment by Gillespie59** [comment]
I think I have finished the migration. Can you have a look and test the migration-1.1.0 branch ?

If is OK for you I will create the 0.5.0 release.

**Comment by AdriVanHoudt** [comment]
Seems to work.
Although not sure why you hard setted all the deps https://github.com/Gillespie59/eslint-plugin-angular/compare/migration-1.1.0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R17
And you missed some new lines at the end of files ;)

**Comment by Gillespie59** [comment]
Hi @AdriVanHoudt 
Thanks for you feedback. I solved these small issues. 

After the next :+1: , I will create the new release ;)

Manu

**Comment by AdriVanHoudt** [comment]
LGTM :shipit:

**Comment by Gillespie59** [comment]
0.5.0 released :d
