### ISSUE TITLE
Create documentation for each rules with examples

### ISSUE THREAD

**Issue by tilmanpotthof** [Gillespie59/eslint-plugin-angular#162]
The way the rules are described on http://eslint.org/docs/rules/ give a great overview, and the further descriptions in the sub pages help to understand the rules in detail.

I'd suggest a folder `documentation` with a markdown file for each rule and a like to the existing list.

**Comment by tilmanpotthof** [comment]
@Gillespie59 @remcohaszing 

I have a draft for a setup to generate documentation from comments and example files. The goal is to have a setup were every code example is tested with the documented configuration and to have a easy mechanism to generate documentation.

- Docs are generated to the `docs/` folder
- Basic documentation is added as comment in the rules themself
- Examples are in the `examples/` folder
- The script to generate the docs can be found in `scripts/docs.js`

https://github.com/Gillespie59/eslint-plugin-angular/compare/master...tilmanpotthof:issue-162/Create-documentation-for-each-rules-with-examples

There are still a lot of examples missing. Therefore I didn't open up a PR. I try to add them this weekend, but it would be great to get some feedback what you think about this approach. Is it to oversized? Were do you see weak spots?

I the long run I want to bring the generated documentation closer to the examples in the eslint docs itself, but for now I started with a bit simpler example style.

**Comment by remcohaszing** [comment]
This is really cool!

Some ideas for improvement popped into my mind:

- Add a standarized way to document and render links to Johnpapa's style guide

  ```
@johnpapa Y181
```

- Comments on shema definitions could be parsed to render documentation on what values are acceptible.

Also a policy should be documented on whether rendered docs **should** or **should not** be committed with changes.

**Comment by tilmanpotthof** [comment]
@remcohaszing Thanks for the input and positive feedback. I like both ideas and will integrate them as soon as possible.

I agree to your policy suggestion. I think the generated docs should be in sync with the source and examples. Probably a pre-commit hook could help to automate or check this.

**Comment by tilmanpotthof** [comment]
@remcohaszing I added a tag to define styleguide references in b0d560c. The syntax is independent from references to johnpapa's styleguid and it is possible to add further sources in the future.

    @styleguideReference {johnpapa} `y040` Services - Singletons

I also added a `@version` tag and looked up the versions for all rules.

**Comment by remcohaszing** [comment]
Nice!
