### ISSUE TITLE
`ng_di_order`: `Cannot read property 'map' of undefined`

### ISSUE THREAD

**Issue by alexlrobertson** [Gillespie59/eslint-plugin-angular#178]
The error is occurring at `rules/ng_di_order.js:21`:

```js
var args = fn.params.map(function(arg) {
                    ^
```

The offending code is:

```js
this.$get = get;
```

This is using:

* eslint-plugin-angular@0.7.0
* eslint@1.2.1

**Comment by Gillespie59** [comment]
@remcohaszing  is this issue resolved with your last PR ?

**Comment by remcohaszing** [comment]
@Gillespie59 Yes it is. It no longer causes an error.

It doesn't check the DI order if a function isn't passed directly though. This requires further introspection.

**Comment by Gillespie59** [comment]
OK perfect ;)
I will publish the 0.8.0 release
