### ISSUE TITLE
Check json schema for config options

### ISSUE THREAD

**Issue by tilmanpotthof** [Gillespie59/eslint-plugin-angular#193]
'file-name' rule has no option schema definition. Check if other schemas are missing as well.

**Comment by Gillespie59** [comment]
some of them do not have Schema def, because it impossible, I think, de define a parameter that can be a string OR a regexp (like controller-name).

**Comment by tilmanpotthof** [comment]
Ok, thanks for the information.

**Comment by remcohaszing** [comment]
This is now better validated, because of #346. It is no longer possible to accept configs which don't exist in the schema. I think this issue can be closed now.

**Comment by remcohaszing** [comment]
Closing this, as I think all schemas are covered now.
