### ISSUE TITLE
Use eslint for rules, tests and gulpfile

### ISSUE THREAD

**Issue by tilmanpotthof** [Gillespie59/eslint-plugin-angular#196]
Some files are inconsistent and eslint might help us.

**Comment by remcohaszing** [comment]
It is a bit ironic that an eslint plugin has such an inconsistent coding style.

I would like to implement this if @Gillespie59 agrees. I'm not sure what the deal is with @Gillespie59 self-assigning this issue and removing the assignment the same day.

**Comment by Gillespie59** [comment]
Yes of course you can implement it @remcohaszing  ! thanks a lot for your amazing job you and @tilmanpotthof . I do not have a lot of time right now :(

**Comment by tilmanpotthof** [comment]
@remcohaszing Would be great if you can fix that. I really had to be careful in some files with mixed spaces and tabs. ;-)

@Gillespie59 Time is limited. We all know that. Thanks for releasing the all he past changes so fast!!!

**Comment by Gillespie59** [comment]
I have juste changed the milestone. Because I won't be able to do release this week. The 0.12.0 release will contain all PR sent next week
