### ISSUE TITLE
Prevent usage of private object (prefixed with $$)

### ISSUE THREAD

**Issue by tilmanpotthof** [Gillespie59/eslint-plugin-angular#202]
Prevent the usage of internal undocumented objects and APIs. Breaking changes are not documented.

**Comment by Gillespie59** [comment]
What is the difference with the https://github.com/Gillespie59/eslint-plugin-angular/blob/master/rules/no-private-call.js rule ?

**Comment by tilmanpotthof** [comment]
There is none. I just haven't checked that one. Sorry...

**Comment by Gillespie59** [comment]
no pb ;)

**Comment by remcohaszing** [comment]
The AngularJS docs state

> **Angular Prefixes `$` and `$$`**: To prevent accidental name collisions with your code, Angular prefixes names of public objects with `$` and names of private objects with `$$`. Please do not use the `$` or `$$` prefix in your code.

https://docs.angularjs.org/api

That rule checks for some specific variable names, while the docs actually state no variables prefixed with `$$` may be used.

**Comment by remcohaszing** [comment]
See #203
