### ISSUE TITLE
no-private-calls: report any property prefixed with $$

### ISSUE THREAD

**Issue by tilmanpotthof** [Gillespie59/eslint-plugin-angular#203]
The rule 'no-private-calls' covers 12 predefined properties, but the internal properties and methods can change in any minor or patch release without any mention in the changelog.

If there are any valid usages for $$-prefixed properties or methods, they should be whitelisted.

**Comment by tilmanpotthof** [comment]
Are their any properties that should be whitelisted?

**Comment by remcohaszing** [comment]
Some libraries use `$$rAF`, though I don't think end users should use it.

**Comment by tilmanpotthof** [comment]
@remcohaszing Ok thanks. I added an 'allow' option, so libs can define their own exceptions.
