### ISSUE TITLE
Using recommended eslint rules along with this plugin

### ISSUE THREAD

**Issue by parky128** [Gillespie59/eslint-plugin-angular#226]
Hi,

I have recently integrated eslint into my angular application and soon realised I needed this repo's plugin in order to get my application to be linted correctly.

Prior to this, I was using the extends property in my `.eslintrc` file and setting to `eslint:recommended` to make use of the eslint recommended rule set. 

````
{
  "extends": "eslint:recommended"
}
````
I tested this worked by adding a trailing comma to an object definition in my code to make sure I saw an error appear from eslint.

Now, following the guides for the eslint-plugin-angular, I have also installed eslint-config-angular and I see that the quickest way to get started is using the shareable config.

If I use the extends angular config option in place of my current:

````
{
  "extends": "angular"
}
````
I no longer get my error thrown for an unexpected trailing comma.

So, is there a way I can use both angular and `eslint:recommended` in the extends config option?
E.g:
````
{
  "extends": ["angular", "eslint:recommended"]
}
````
(which I know does not work)

If not, does this mean I have to create a rules config object in my `.eslintrc` to mimic the recommended ones from eslint?
````
{
  "extends": "angular",
  "rules" : {
    ...
  }
}
````

**Comment by tilmanpotthof** [comment]
According to the latest eslint documentation and a local setup test, it is possible to configure extends as array like you described it.

You probably need to upgrade to the latest eslint version.

http://eslint.org/docs/user-guide/configuring#extending-configuration-files
