### ISSUE TITLE
function-type rule does not recognize inline named functions properly

### ISSUE THREAD

**Issue by jeffcharles** [Gillespie59/eslint-plugin-angular#229]
I have some code that looks like this:

`.factory('myHttpInterceptor', function myHttpInterceptor($localStorage, configuredToken) {`

and I'm getting an error on the module indicating that I should use a named function instead of an anonymous function. I wasn't expecting that error because the function is named.

The code for the rule looks like it has an error https://github.com/Gillespie59/eslint-plugin-angular/blob/044621cd4f1a93f4f4087b2472efca034e431012/rules/function-type.js#L24. The second argument could be a named function or an identifier and be in compliance. Furthermore, the use of an identifier doesn't necessarily mean the function is named since it's possible to assign an anonymous function to a variable.

**Comment by tilmanpotthof** [comment]
Thanks for the detailed description. I can reproduce the behavior in a unit test.

**Comment by tilmanpotthof** [comment]
Should be fixed in the next version.

https://github.com/Gillespie59/eslint-plugin-angular/pull/235

**Comment by tilmanpotthof** [comment]
PR is merged.
