### ISSUE TITLE
angular/on-watch error

### ISSUE THREAD

**Issue by tossp** [Gillespie59/eslint-plugin-angular#231]
hi,guys
How do I fix this error？

Error Messages：
```
  131:7  error  The "$on" call should be assigned to a variable, in order to be destroyed during the $destroy event  angular/on-watch
  140:7  error  The "$on" call should be assigned to a variable, in order to be destroyed during the $destroy event  angular/on-watch
  145:7  error  The "$on" call should be assigned to a variable, in order to be destroyed during the $destroy event  angular/on-watch
  150:7  error  The "$on" call should be assigned to a variable, in order to be destroyed during the $destroy event  angular/on-watch
```
Corresponding Source：
```java
      $rootScope.$on('$stateChangeStart', function (event, toState) {
        //$log.debug(1, '$stateChangeStart', event, toState, toParams, fromState, fromParams);

        handleHtmlId(toState);
        detachOnResize();
      });

      // initialized with 1 cause we came here with one $viewContentLoading request
      var viewContentLoading = 1;
      $rootScope.$on('$viewContentLoading', function () {
        //$log.debug(2, '$viewContentLoading', event, viewConfig);
        viewContentLoading++;
      });

      $rootScope.$on('$stateChangeSuccess', function () {
        //$log.debug(3, '$stateChangeSuccess', event, toState, toParams, fromState, fromParams);
        forceResizeTrigger = true;
      });

      $rootScope.$on('$viewContentLoaded', function () {
        //$log.debug(4, '$viewContentLoaded', event);
        viewContentLoading--;

        if (viewContentLoading === 0 && initialized) {
          debouncedRun();
        }
      });
```

**Comment by tilmanpotthof** [comment]
Documentation: https://docs.angularjs.org/api/ng/type/$rootScope.Scope - Returns a deregistration function for this listener.

    var deregisterationCallback = $rootScope.$on(....
    $rootScope.$on('$destroy', deregistrationCallback)

http://stackoverflow.com/questions/25113884/should-angular-watch-be-removed-when-scope-destroyed

**Comment by tossp** [comment]
@tilmanpotthof Thank you very much!

**Comment by gitnik** [comment]
Does this really make sense? Shouldn't this lint ignore the `$rootScope`. Destroying the `$rootScope` implies the app being teared down, which makes unsubscribing kinda useless

**Comment by gitnik** [comment]
I would love to submit a PR if this behaviour is not wanted

**Comment by tilmanpotthof** [comment]
@gitnik Good point. I think unsubscribing from the $rootScope does not make sense, at least with the `$destroy` event.

... or did I miss something? @remcohaszing @Gillespie59

**Comment by remcohaszing** [comment]
Seems legit.

**Comment by gitnik** [comment]
OK I will submit a PR then :-)

**Comment by gitnik** [comment]
Shouldn't this actually only lint `on`? Removing `$watch` is not needed, as the previously SO answer already explains

**Comment by laurent-le-graverend** [comment]
:+1:

**Comment by gitnik** [comment]
https://github.com/Gillespie59/eslint-plugin-angular/pull/264

**Comment by charneykaye** [comment]
Any reason not to do this?

    $rootScope.$on('$destroy', $rootScope.$on(EVENTS.changeRegion, function() {
      vm.nowRegion = OpsService.getRegion();
    }));
