### ISSUE TITLE
angular.isRegexp is no angular function

### ISSUE THREAD

**Issue by tilmanpotthof** [Gillespie59/eslint-plugin-angular#233]
The `angular.isRegexp` function seems to belong to a third party module: https://github.com/pbakondy/angular-typecheck

It should be deprecated and moved to another project or at least mentioned in the docs.

**Comment by Gillespie59** [comment]
I neve realized thius method never exist. I do not why I have created this rule :D. I think we should deprecated this rule.

**Comment by Gillespie59** [comment]
I will deprecate the rule for the 0.13.0 release, but keep this issue opened in order to remember than we have to remove it for the 1.0.0 release.

**Comment by Gillespie59** [comment]
Duplicate : #298
