### ISSUE TITLE
Cannot find module 'eslint-plugin-angular'

### ISSUE THREAD

**Issue by Offirmo** [Gillespie59/eslint-plugin-angular#234]
I tried eslint-plugin-angular but I don't want it anymore (for now)

I've removed it from .eslintrc config (plugin [] )

I've removed it from my dependencies (both in package.json and with npm prune)

However when I run eslint (local), it fails, still asking for eslint-plugin-angular

How is it possible ??

**Comment by tilmanpotthof** [comment]
Is it possible that you still have rules configured in .eslintrc? Removing the plugin is not enough, if you configured some rule.

**Comment by Offirmo** [comment]
Thanks. But I already commented out all the rules refering to angular...

**Comment by Offirmo** [comment]
Found the problem : a sub-module not outside eslint reach is asking for angular plugin.

thanks

**Comment by tilmanpotthof** [comment]
Allright.
