### ISSUE TITLE
on-watch false positive when using event name from constant

### ISSUE THREAD

**Issue by vrockai** [Gillespie59/eslint-plugin-angular#256]
I got several of these errors:
`N:M  error  The "$on" call should be assigned to a variable, in order to be destroyed during the $destroy event  angular/on-watch`

only because I've put all my event name strings into constants, so I deregister events like this:
`$rootScope.$on(myEventNameConstants.scope.destroy, foo);`

Workaround:
Don't use variable for the '$destroy' event name.

**Comment by Gillespie59** [comment]
I have just checked, and the problem do not come from the constant. You should assign the result of the `$on` method to a variable, that will be use later in order to remove all useless data.

**Comment by Gillespie59** [comment]
`var v = $rootScope.$on(myEventNameConstants.scope.destroy, foo);` for example

**Comment by tilmanpotthof** [comment]
@vrockai Did the answer work for you?

I'll close this issue. Please reopen it with a comment, if you disagree.
