### ISSUE TITLE
Do not enable rules be default

### ISSUE THREAD

**Issue by palortoff** [Gillespie59/eslint-plugin-angular#258]
eslint built-in rules are not enabled by default.

By enabling rules by default you force projects that do not want to enable all the recommended rules to clutter the eslint configuration file with deactivated rules.

**Comment by remcohaszing** [comment]
I totally agree.

This would be a breaking change though. I suggest to implement this for version 1.0.0.

**Comment by palortoff** [comment]
I just created [eslint-plugin-angular-off](https://github.com/palortoff/eslint-plugin-angular-off) as a wrapper with all rules disabled by default.

**Comment by tilmanpotthof** [comment]
+1

Thanks for the pragmatic solution until 1.0.0.

**Comment by maksimr** [comment]
+1

**Comment by AdriVanHoudt** [comment]
well Eslint does have an recommended you can extend, maybe this can be added (because I did like the defaults and now I have to set them manually)
