### ISSUE TITLE
component-limit false positives

### ISSUE THREAD

**Issue by tilmanpotthof** [Gillespie59/eslint-plugin-angular#259]
The following examples are detected as components and therefore exceed the component limit.

    app.service("", function(myService) { var data = {}; myService.someMethod("", data); });

... second example ...

   $httpBackend.expectGET("").respond(200, dummyData);
   $httpBackend.expectGET("").respond(200, dummyData);

The reason seem to be the misleading utils method `utils.isAngularComponent` used in the `component-limit rule.

I'll add a failing test case.

**Comment by remcohaszing** [comment]
#283 doesn't fix this issue, but it does issue no longer exists in the development branch.
