### ISSUE TITLE
Keep defaults in README consistent with those from index.js

### ISSUE THREAD

**Issue by tilmanpotthof** [Gillespie59/eslint-plugin-angular#261]
There are some inconsistencies between the defaults in the README and the index.js. 

```
rulesConfiguration.addRule('watchers-execution', [0, '$destroy']);

"angular/watchers-execution": [0, "$digest"],
```

The sections should be generated by the docs task like the rules section.

**Comment by Gillespie59** [comment]
I think this issue is not true anymore. I do not see this information in the REDME file.
