### ISSUE TITLE
Example parser does not allow examples with multiple errors

### ISSUE THREAD

**Issue by palortoff** [Gillespie59/eslint-plugin-angular#268]

**Comment by tilmanpotthof** [comment]
That's for the report. I'll have a look at this issue.

**Comment by tilmanpotthof** [comment]
@palortoff Can you please add your use case as comment? It was quite easy to make add multiple errors for the documentation test, but I fear it's complicated to generate good examples in the documentation. A specific use case could help to reason about this.

**Comment by palortoff** [comment]
@tilmanpotthof 

for the new rule in PR #269 I would have liked to have made the example

```javascript
// example - valid: false, errorMessages: ["Do not use multiple dependencies in one line", "Do not use multiple dependencies in one line"]

app.controller('MyController', ['$http', '$q', function($http, $q) {}]);
```

This would have failed on ``'$q'`` and ``$q``

**Comment by tilmanpotthof** [comment]
@palortoff Ok, I understand. I'll add this feature to the docs script.

**Comment by maksimr** [comment]
@tilmanpotthof what about this issue? It seems this issue stop publishing 0.14 version.

**Comment by tilmanpotthof** [comment]
@maksimr Thanks for the reminder. I could not decide between errorMessage and errorMessages ;-) I opened a PR.

**Comment by Gillespie59** [comment]
I think we can now close this issue ? as I have merged you PR.

**Comment by tilmanpotthof** [comment]
I think the PR fixes everything described by @palortoff

If anyone disagree, please reopen the issue.
