### ISSUE TITLE
Use component API instead of the directive API 

### ISSUE THREAD

**Issue by Gillespie59** [Gillespie59/eslint-plugin-angular#271]
With AngularJS 1.5, we have now a new way to create directive, thanks to a new `component` method. This method will make the migration to Angular2 easier. 
We should create a rule that will verify the use of this new method instead of the old one.

**Comment by tilmanpotthof** [comment]
I think we should add a tag to the documentation for which angular versions a rule makes seance, to help users to identify useful rules for their project.

**Comment by Gillespie59** [comment]
+1
Should we use the angular setting I have already defined in order to detect Angular 1 or 2 ? 
This value could be equal to any Angular version : 1.4, 1.5 or 2
What do you think ?

**Comment by tilmanpotthof** [comment]
I opened a ticket for this.

https://github.com/Gillespie59/eslint-plugin-angular/issues/274

**Comment by TuckerWhitehouse** [comment]
Component can only be used in cases where a "link" function is not required (no dom manipulation). So `angular.directive` is still required for interaction with the dom. Maybe a "prefer-component" rule that would suggest the `angular.component` syntax if a link function is not found?

**Comment by Gillespie59** [comment]
You are totally right @TuckerWhitehouse . Thanks for these remarks. We will rename the rule, and try to detech the use or not of a `link` function

**Comment by la-yumba** [comment]
+1

**Comment by ukupat** [comment]
+1
