### ISSUE TITLE
README.md no longer references John Papa's Style Guide

### ISSUE THREAD

**Issue by Sandstone-WeiWenHo** [Gillespie59/eslint-plugin-angular#288]
The **Rules** section in `README.md` no longer contains references to which John Papa Style Guide Rule they implement (where relevant).

* Is this intended?
* If so, then the **Summary** needs to be updated as well, since it mentions that

> Since the 0.0.4 release, some rules defined in John Papa's Guideline have been implemented. In the description below, **you will have a link to the corresponding part of the guideline**, in order to have more information.

I see that the references to the John Papa Style Guide are now included in the individual `*.md` files, but I personally found it a lot more helpful to have them on the `README.md`, since that allowed me to immediately identify which Rules were from the John Papa Style Guide.

**Comment by tilmanpotthof** [comment]
Thanks for the report. It was intended to shorten the section and put the details into separate pages, but I see no problem the add a short note to the descriptions.

The docs are now generated and we just have to change the template for the rules section.

**Comment by tilmanpotthof** [comment]
PR #289
