### ISSUE TITLE
AngularJS Style Guide

### ISSUE THREAD

**Issue by albertosantini** [Gillespie59/eslint-plugin-angular#29]
Any roadmap to implement John Papa's AngularJS Style Guide?

https://github.com/johnpapa/angularjs-styleguide

**Comment by Gillespie59** [comment]
Hi Albert,

Will have a look to this well-known guideline. I think some of these BP are already implemented. But will let you know soon about the roadmap. 

Manu

**Comment by albertosantini** [comment]
Thanks for the quick reply.
Your plugin is AngularJS Nirvana. :)

**Comment by Gillespie59** [comment]
Thanks a lot. 
If you want to collaborate, do not hesitate to send Pull Request ;)

**Comment by Gillespie59** [comment]
* Define 1 component per page (Y001) -> eslint-plugin-angular 0.0.5 (Difficulty: 1/5)
* JavaScript Closures IIFE (Y010) -> should be implemented in ESLint
* Definitions (aka Setters) (Y021) -> eslint-plugin-angular 0.0.5 (Difficulty: 1/5)
* Getters (Y022) -> eslint-plugin-angular 0.0.5 (Difficulty: 1/5)
* Named vs Anonymous Functions (Y024) -> [eslint-plugin-angular 0.0.5](https://github.com/Gillespie59/eslint-plugin-angular/issues/13) (Difficulty: 2/5) 
* controllerAs Controller Syntax (Y031) -> eslint-plugin-angular 0.0.5 (Difficulty: 1/5)
* controllerAs with vm (Y032) -> eslint-plugin-angular 0.0.5 (Difficulty: 1/5)
* Bindable Membert Up Top (Y033) -> eslint-plugin-angular 0.0.6 (Difficulty 5/5)
* Function Declarations to Hide Implementation Details (Y034) -> eslint-plugin-angular 0.0.6 (Difficulty 5/5)
* Defer Controller Logic (Y035) -> [eslint-plugin-angular 0.0.4](https://github.com/Gillespie59/eslint-plugin-angular/issues/11). Need to add $q to the list.
* Keep Controllers Focused (Y037) -> eslint-plugin-angular 0.0.6 (Difficulty: 4/5)
* Assigning Controllers (Y038) -> eslint-plpugin-angular 0.0.6 (Difficulty: 5/5)
* Singletons (Y040) -> eslint-plugin-angular 0.0.5 (Difficulty 1/5)
* Accessible Members Up Top (Y052) -> eslint-plugin-angular 0.0.6 (Difficulty: 5/5)
* Function Declarations to Hide Implementation Details (Y053) -> eslint-plugin-angular 0.0.6 (Difficulty 5/5)
* Return a promise from Data Calls (Y061) -> Impossible
* Directives - Limit 1 Per File (Y070) -> eslint-plugin-angular 0.0.5 (Difficulty: 1/5)
* Manipulate DOM in a Directive (Y072) -> [eslint-plugin-angular 0.0.6](https://github.com/Gillespie59/eslint-plugin-angular/issues/22) (Difficulty: 3/5)
* Provide a Unique Directive Prefix (Y073) -> [eslint-plugin-angular 0.0.4](https://github.com/Gillespie59/eslint-plugin-angular/issues/10)
* Restrict to Elements and Attributes (Y074) -> [eslint-plugin-angular 0.0.5](https://github.com/Gillespie59/eslint-plugin-angular/issues/23) (Difficulty: 2/5)
* Directives and ControllerAs (Y075) -> eslint-plugin-angular 0.0.5 (Difficulty: 2/5)
* Controller Activation Prommises (Y080) -> eslint-plugin-angular 0.0.5 (Difficulty 3/5)
* Route Resolve Promises (Y081) -> eslint-plugin-angular 0.0.5 (Difficulty: 3/5)
* Manually Identify Dependencies (Y091) -> eslint-plugin-angular 0.0.5 (Difficulty; 4/5)
* Route Errors (Y112) -> eslint-plugin-angular 0.0.6 (Difficulty: 2/5)
* Naming Guidelines (Y120) and Feature File Names (Y121) -> eslint-plugin-angular 0.0.6 (Difficulty: 4/5)
* Test File Names (Y122) -> eslint-plugin-angular 0.0.7 (Difficulty: 4/5)
* Controller Names (Y123) -> [eslint-plugin-angular 0.0.4](https://github.com/Gillespie59/eslint-plugin-angular/issues/10)
* Controller Name Suffix (Y124) -> [eslint-plugin-angular 0.0.4](https://github.com/Gillespie59/eslint-plugin-angular/issues/10)
* Factory Names (Y125) -> [eslint-plugin-angular 0.0.4](https://github.com/Gillespie59/eslint-plugin-angular/issues/10)
* Directive Component Names (Y126) -> [eslint-plugin-angular 0.0.4](https://github.com/Gillespie59/eslint-plugin-angular/issues/10)
* Modules (Y127) -> [eslint-plugin-angular 0.0.4](https://github.com/Gillespie59/eslint-plugin-angular/issues/10)
* Configuration (Y128) -> eslint-plugin-angular 0.0.7 (Difficulty: 3/5)
* Routes(Y129) -> eslint-plugin-angular 0.0.7 (Difficulty: 3/5)
* Run Blocks (Y171) -> eslint-plugin-angular 0.0.7 (Difficulty: 2/5)
* $document and $window (Y180) -> [eslint-plugin-angular 0.0.4](https://github.com/Gillespie59/eslint-plugin-angular/issues/16)
* $timeout and $interval (Y181) -> [eslint-plugin-angular 0.0.4](https://github.com/Gillespie59/eslint-plugin-angular/issues/17)
* Routing - User AngularUI Router (Y280) -> eslint-plugin-angular 0.0.4 (Difficulty: 2/5)

**Comment by Gillespie59** [comment]
Hi, 

Here is my roadmap. Any remarks are welcomed ;)

If everything is OK for you, I will deploy the release 0.0.4, create an issue for all of these items, and start working on them.

**Comment by albertosantini** [comment]
Great! Go ahead.
I have been using the plugin to lint Argo: https://github.com/albertosantini/argo

**Comment by Gillespie59** [comment]
I have created all tickets for all these new features. 
Feel free to send Pull request ;)

**Comment by johnpapa** [comment]
Are these implemented yet or just issues created?

**Comment by Gillespie59** [comment]
Some of them have already been implemented. Need to add a link to your awesome guideline. 
But a huge list of best practice need to be implemented ;) Will do it soon.

**Comment by johnpapa** [comment]
is it ready to test? id like to show it if its ready

**Comment by Gillespie59** [comment]
You can maybe have a look to these rules : 
- ng_controller_name
- ng_directive_name
- ng_filter_name
- ng_interval_service
- ng_module_name
- ng_no_services
- ng_service_name
- ng_timeout_service
- ng_window_service

**Comment by johnpapa** [comment]
i couldnt get it working. let me know when its closer. this is a great idea.

**Comment by Gillespie59** [comment]
Which error do you have ? Albert an I used it for personnal project. 

Maybe you use the 0.0.3 release, because the 0.0.4 has not been deployed it. Maybe you can install via the Github URL ? 

I will deploy the release 0.0.4 today or tomorrow.

**Comment by johnpapa** [comment]
I did it from github. For errors about some of the rules not being found. 

There were some spelling mistakes. I fixed some but ran into other others about rules not being found. 



John 



On Mar 4, 2015, at 12:16 AM, Emmanuel DEMEY <notifications@github.com> wrote:

Which error do you have ? Albert an I used it for personnal project.

Maybe you use the 0.0.3 release, because the 0.0.4 has not been deployed it. Maybe you can install via the Github URL ?

I will deploy the release 0.0.4 today or tomorrow.

**Comment by albertosantini** [comment]
Indeed see https://github.com/Gillespie59/eslint-plugin-angular/issues/57

**Comment by johnpapa** [comment]
See the issues I am having here https://github.com/Gillespie59/eslint-plugin-angular/issues/57
