### ISSUE TITLE
Disallow $filter

### ISSUE THREAD

**Issue by remcohaszing** [Gillespie59/eslint-plugin-angular#322]
Let's say we have a module defining a filter:
```js
angular.module('filters', [])

.filter('coffeeFilter', function() {
  ...
});
```

A service can depend on this in two ways:
```js
angular.module('devTools', [])

.factory('coffeeMachine', function(coffeeFilterFilter) {
  function getCoffee() {
    return coffeeFilterFilter(water);
  }
})
```
```js
angular.module('devTools', [])

.factory('coffeeMachine', function($filter) {
  function getCoffee() {
    return $filter('coffeeFilter')(water);
  }
})
```

Both services will throw an error though, because they should depend on the `filters` module.

The first one will throw an error upon dependency injection. The second one when the filter is used.

I think it makes sense to disallow the use use `$filter` to avoid this type of situations. I'm not sure if it's better to make this a separate rule or to include it by default in the `no-services` rule. If it's included by default in `no-services`, this would be a breaking change, so it should be part of the `1.0.0` release.

@Gillespie @tilmanpotthof Any thoughts?

**Comment by tilmanpotthof** [comment]
Your main problem with $filter is, that you get errors only when you run the getCoffee Method, right?

I think this problem can be covered by the `no-services` and we could document it there.

**Comment by tilmanpotthof** [comment]
@remcohaszing I updated you example. The DI for the coffeeFilter must be named coffeeFilterFilter.

**Comment by remcohaszing** [comment]
> Your main problem with $filter is, that you get errors only when you run the getCoffee Method, right?

That's right. I think this would be a sane default for the `no-services` rule.

**Comment by tilmanpotthof** [comment]
@remcohaszing +1 - Sane defaults might be a topic for #323
