### ISSUE TITLE
Update README.md -> Defaults section to use ""angular" instead of ""angular/angular"

### ISSUE THREAD

**Issue by shaggyshelar** [Gillespie59/eslint-plugin-angular#327]
Hi, I tried using configuration mentioned in Defaults but was getting error, so when I changed "angular/angular" to ""angular" it worked for me. Please check.

**Comment by tilmanpotthof** [comment]
Thanks for the report. What error did you get? Which eslint version do you use? What is your setup (grunt, gulp, eslint from the commandline)?

**Comment by Gillespie59** [comment]
I think you should use an old version of the plugin. Do you ?

**Comment by fchiumeo** [comment]
in readmee.md ##Defaults section [angular/angular](https://github.com/Gillespie59/eslint-plugin-angular/blame/master/README.md#L99)

**Comment by Gillespie59** [comment]
Oh I understand.
