### ISSUE TITLE
Consistenly use JSON or YAML syntax for .eslintrc

### ISSUE THREAD

**Issue by remcohaszing** [Gillespie59/eslint-plugin-angular#328]
It is possible to use either JSON or YAML syntax in `.eslintrc` files. In the readme, both are used for different examples. Our own `.eslintrc` file uses YAML syntax.

I personally prefer YAML, because it allows the use of comments, but I think consistency is more important.

I'm not sure how this affects the generated defaults in the readme introduced in #275.

**Comment by Gillespie59** [comment]
:+1: for YAML format

**Comment by brutalcrozt** [comment]
`1.0.0` already [use](https://github.com/Gillespie59/eslint-plugin-angular/blob/1.0/.eslintrc.yaml) yaml :+1:

**Comment by Gillespie59** [comment]
Is this update enough ?

**Comment by remcohaszing** [comment]
Partially.

Default values are still generated as JSON.

However, I suggest removing defaults entirely because of #345.

**Comment by remcohaszing** [comment]
This is now resolved, because the defaults are no longer in the readme.
