### ISSUE TITLE
Add rule for detecting missing dependency

### ISSUE THREAD

**Issue by manast** [Gillespie59/eslint-plugin-angular#333]
Maybe I missed this feature, but at least I am not able to get eslint to complain to code like this:

```javascript
app.config(['$urlRouteProvider', function($urlRouteProvider, $timeout){
...
}])
```
I expect eslint to complain that $timeout is not declared. This would be quite useful since apps just breaks when minified if you happen to forget a dependency.

**Comment by remcohaszing** [comment]
I agree. This is actually a pretty trivial rule. The rule shouldn't necessarily check for missing di declarations, but any type of mismatch. This includes a wrong order:

```js
app.config(['$timeout', '$urlRouteProvider', function($urlRouteProvider, $timeout){
...
}])
```

And an extraneous di declaration:
```js
app.config(['$urlRouteProvider', '$timeout', function($urlRouteProvider){
...
}])
```

**Comment by jmayday** [comment]
+1
