### ISSUE TITLE
Controller as vm on angular.foreach don't pass when use context

### ISSUE THREAD

**Issue by brutalcrozt** [Gillespie59/eslint-plugin-angular#339]
as the [angular doc foreach](https://docs.angularjs.org/api/ng/function/angular.forEach) say
![eslint-plugin-angular](https://cloud.githubusercontent.com/assets/3001652/13032999/ddb51b08-d339-11e5-8b52-fda1bd2ff661.PNG)

IMO this should passed.

**Comment by Gillespie59** [comment]
But as you use vm.activeData below, I think, in my opinin, that's better to use the syntax everywhere ;

**Comment by brutalcrozt** [comment]
sorry what you mean by `syntax everywhere`

**Comment by remcohaszing** [comment]
I agree with @Gillespie59 here. Since this rule is based on [Y032](https://github.com/johnpapa/angular-styleguide#style-y032), I suggest to move this discussion there and close this issue until a discussion there results otherwise.

**Comment by brutalcrozt** [comment]
i mean it will be great if improve the plugin?
if you both agree to close it, i will do it :smile:

**Comment by remcohaszing** [comment]
> i mean it will be great if improve the plugin?

What do you mean by that?

I think the changes you're suggesting would oppose the goal of this rule. You shouldn't use `this` for referencing the view model. Closing this issue until a discussion on John Papa's style guide proves otherwise.
