### ISSUE TITLE
Getters (Y022)

### ISSUE THREAD

**Issue by Gillespie59** [Gillespie59/eslint-plugin-angular#34]
https://github.com/johnpapa/angularjs-styleguide/edit/master/README.md

- When using a module, avoid using a variable and instead use chaining with the getter syntax.

  *Why?*: This produces more readable code and avoids variable collisions or leaks.

  ```javascript
  /* avoid */
  var app = angular.module('app');
  app.controller('SomeController', SomeController);

  function SomeController() { }
  ```

  ```javascript
  /* recommended */
  angular
      .module('app')
      .controller('SomeController', SomeController);

  function SomeController() { }
  ```

**Comment by borislavjivkov** [comment]
I want to take this issue if it's ok.

**Comment by Gillespie59** [comment]
No pb for me @borislavjivkov . Thanks a lot. 

I have created a new branch : 0.0.8. All new changes should be pushed into this branch.

Manu
