### ISSUE TITLE
SyntaxError in /rules/utils/angular-rule.js

### ISSUE THREAD

**Issue by kurakin-oleksandr** [Gillespie59/eslint-plugin-angular#353]
There is an error:
`node_modules/eslint-plugin-angular/rules/utils/angular-rule.js:199
});
^
SyntaxError: Failed to load plugin angular: Unexpected token }`

**Comment by remcohaszing** [comment]
I find it hard to believe there is a syntax error. The code is linted using ESLint.

Also line 199 doesn't contain `}); ^`.

Did you modify this file? Perhaps by accident? I suggest to remove the `node_modules/eslint-plugin-angular` directory and run `npm install` again.

**Comment by kurakin-oleksandr** [comment]
Yes, you're right. File itself is ok. I'll investigate problem.
Thanks for quick answer!
