### ISSUE TITLE
Possible to remove lodash

### ISSUE THREAD

**Issue by eddiemonge** [Gillespie59/eslint-plugin-angular#357]
Doesn't seem like lodash is providing much for the actual module. Think it could be removed to help cut down the dependency tree?

**Comment by brutalcrozt** [comment]
agree, waiting the team to discus about this :smile:

**Comment by remcohaszing** [comment]
I agree this dependency is a bit overkill. It is only used by [one-dependency-per-line](https://github.com/Gillespie59/eslint-plugin-angular/blob/master/rules/one-dependency-per-line.js).

It is also used in some [scripts](https://github.com/Gillespie59/eslint-plugin-angular/tree/master/scripts), but that would just make it a devDependency, which is not as bad.

I'd love to see a PR demoting it to a devDependency. Although getting rid of it as a devDependency would be fine with me as well. :wink:

**Comment by Gillespie59** [comment]
Just moved lodash as a devDep
