### ISSUE TITLE
controller-name default validation

### ISSUE THREAD

**Issue by darlanmendonca** [Gillespie59/eslint-plugin-angular#359]
Instead validate by /[A-Z].*Controller$/, the default pattern is /[A-Z].*Controller.*/

This is right?

I want made a pull request to fix it to follow /[A-Z].*Controller$/ by default, if you wants too

**Comment by Gillespie59** [comment]
I think you are right ! The controller should end with "Controller"
Le 26 févr. 2016 9:28 PM, "Darlan Mendonça" <notifications@github.com> a
écrit :

**Comment by darlanmendonca** [comment]
ok, I will made a pull request, and we see

Congratulations for project!! I loved

**Comment by bastienmoulia** [comment]
I think it's more like `/^[A-Z].*Controller$/`

**Comment by JoernBerkefeld** [comment]
@bastienmoulia is right. as of now it is accepting `myBadlyNamedController` as well as `MyCorrectController` due to the missing `^` at the beginning

the most correct check would probably be `/^[A-Z][a-zA-Z0-9]*Controller$/`, otherwise `_` would be allowed, also breaking the UpperCamelCase rule
