### ISSUE TITLE
[file-name] - change componentTypeMappings object by configuration

### ISSUE THREAD

**Issue by Pencroff** [Gillespie59/eslint-plugin-angular#372]
Hello.
Thank you for cool set of rules.
Is it possible to override `componentTypeMappings` by some configuration settings. For example I would like to separate file names for `factories` and `services` like `user.factory.js` and `auth.service.js` for declare by file name expectable structure inside.

**Comment by tilmanpotthof** [comment]
What approach would you prefer.

(a) General configurability with a new parameter to override the componentTypeMappings

    ["error", {nameStyle: 'dash', componentTypeMappings: {factory: "factory"}}]

(b) Boolean parameter "unifyServiceNames" to specify if all services (factory, value etc.) types are named "service". The default would be true to keep the default behaviour

    ["error", {nameStyle: 'dash', unifyServiceNames: false}]

**Comment by Pencroff** [comment]
I think first approach has more room in future and it's matched with my request.

Thank you for response.

**Comment by tilmanpotthof** [comment]
I implemented the feature in a branch.

Please check the docs if the configuration fits your needs and if the documentation explains the feature good enough.

https://github.com/Gillespie59/eslint-plugin-angular/blob/issue/372-config-for-component-type-mappings/docs/file-name.md

**Comment by Pencroff** [comment]
It looks good for me.
Thank you for great work!

**Comment by tilmanpotthof** [comment]
@Gillespie59

PR is open https://github.com/Gillespie59/eslint-plugin-angular/pull/406

**Comment by Gillespie59** [comment]
Thanks
