### ISSUE TITLE
Edit rules file-name and component-limit to allow .component from angular 1.5

### ISSUE THREAD

**Issue by bastienmoulia** [Gillespie59/eslint-plugin-angular#380]
In angular 1.5 there is a new component available: https://docs.angularjs.org/guide/component

In some rules it is not recognise:
- the file-name rules don't suggest a correct name.
- the component-limit don't detect it
- maybe other rules are impacted

**Comment by LPCmedia** [comment]
added in https://github.com/Gillespie59/eslint-plugin-angular/pull/388

**Comment by Gillespie59** [comment]
Rules updated
