### ISSUE TITLE
module dependency order fails when undefined modules are specified

### ISSUE THREAD

**Issue by DreamingMatt** [Gillespie59/eslint-plugin-angular#383]
For some reason Angular functions fine when one creates a module like this:
 ```
angular.module('undefined-dependencies', [,]);
```
eslint-plugin-angular however does not and fails on the following:
```
eslint-plugin-angular/rules/module-dependency-order.js:48
      if (node.type !== 'Literal') {
                  ^
TypeError: Cannot read property 'type' of null
```

My guess is that there should be a rule which does not allow to add undefined dependencies to an angular module.

**Comment by Gillespie59** [comment]
I think the problem come from the comma inside the dependencies array. 
I am currently working on this issue.
