### ISSUE TITLE
angular style link is not available anymore

### ISSUE THREAD

**Issue by y8n** [Gillespie59/eslint-plugin-angular#384]
angular style link( [https://github.com/johnpapa/angular-styleguide](https://github.com/johnpapa/angular-styleguide) ) used in README is not available. Use [https://github.com/johnpapa/angular-styleguide/blob/master/a1](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md) instead.

**Comment by Gillespie59** [comment]
Done. thanks.
