### ISSUE TITLE
no-private-call is being enforced on non-angular properties

### ISSUE THREAD

**Issue by gumallett** [Gillespie59/eslint-plugin-angular#391]
The description of the no-private-call rule says: "All scope's properties/methods starting with $$ are used internally by AngularJS. You should not use them directly."

However, the way that the rule gets enforced does not match the description.  It seems that **any** properties prefixed with '$$' get flagged, not just angular scope properties.  My specific use case is ui-grid's treeView has a $$treeLevel property.  I cannot modify this property when this rule is enabled, e.g this gives a warning:

node.$$treeLevel = 1

So a property that has nothing to do with angular or $scope can still be flagged by this rule, which seems like a bug to me.

**Comment by Gillespie59** [comment]
You can aldready specify this specific ui-grid $$-prefixed variable as an option to this rule. Check the unit test I have just added to this rule.
