### ISSUE TITLE
is there way to prevent to use of $log ?    no-log / no-console

### ISSUE THREAD

**Issue by gaboesquivel** [Gillespie59/eslint-plugin-angular#397]
I would like to disable the use of $log, is there a way to do it ?

**Comment by remcohaszing** [comment]
You can use [no-services](https://github.com/Gillespie59/eslint-plugin-angular/blob/master/docs/no-services.md) to disallow injecting the `$log` service.

**Comment by gaboesquivel** [comment]
grt, thanks!
