### ISSUE TITLE
Please support ESLint v3.x.x

### ISSUE THREAD

**Issue by qar** [Gillespie59/eslint-plugin-angular#404]

**Comment by Gillespie59** [comment]
Do you have any  problem with the v3.x.x ?

**Comment by qar** [comment]
@Gillespie59 No, there isn't.

I was using v1.3.0 (which use ESLint v2) and thought that was the latest version.

Sorry for my ignorance. I will close this issue.

![image](https://cloud.githubusercontent.com/assets/2390326/17089973/7fb21890-525e-11e6-89c3-bc4a5e4087c4.png)
