### ISSUE TITLE
Utils.convertStringToRegex method removes the last character from a RegExp string.

### ISSUE THREAD

**Issue by K1ll3rF0x** [Gillespie59/eslint-plugin-angular#416]
When defining e.g. a rule: `"angular/controller-name": [2, '/^Prefix[A-Z][a-zA-Z0-9]*Suffix$/']`
A controller name such as 'PrefixBananaSuffixasdf' does not produce errors.

This seems to be caused by a bug in utils.convertStringToRegex function, that removes the last character from the regexp string, in this case the dollar sign.

Version: 1.4.1.

**Comment by Gillespie59** [comment]
I have reproduced the problem. I gonna work on that today I think

**Comment by Gillespie59** [comment]
@K1ll3rF0x I have just pushed a fix on the dev branch ? Can you test it ?
