### ISSUE TITLE
Assigning custom regex to rules like controller name

### ISSUE THREAD

**Issue by gauravsoni1** [Gillespie59/eslint-plugin-angular#419]
Is there a way to customize the pattern for the rules like Controller names ?

Currently `loginController` throws an error as it requires the following syntax `LoginController`.

**Comment by Gillespie59** [comment]
Have you checked this page ? https://github.com/Gillespie59/eslint-plugin-angular/blob/master/docs/component-name.md

You can maybe use a regexp.

**Comment by Gillespie59** [comment]
I have just pushed a new unit test for your use case. you should use this pattern "'/[a-zA-Z].*Controller$/'" in order to accept lowercase and/or uppercase for your controllers
