### ISSUE TITLE
Singletons (Y040)

### ISSUE THREAD

**Issue by Gillespie59** [Gillespie59/eslint-plugin-angular#42]
https://github.com/johnpapa/angularjs-styleguide/edit/master/README.md

- Services are instantiated with the `new` keyword, use `this` for public methods and variables. Since these are so similar to factories, use a factory instead for consistency.

    Note: [All AngularJS services are singletons](https://docs.angularjs.org/guide/services). This means that there is only one instance of a given service per injector.

  ```javascript
  // service
  angular
      .module('app')
      .service('logger', logger);

  function logger() {
    this.logError = function(msg) {
      /* */
    };
  }
  ```

  ```javascript
  // factory
  angular
      .module('app')
      .factory('logger', logger);

  function logger() {
      return {
          logError: function(msg) {
            /* */
          }
     };
  }
  ```

**Comment by jesujcastillom** [comment]
Is there a way to override this rule? I'm defining my services with a class, and would like to keep using the [service method instead of factory ](https://github.com/toddmotto/angularjs-styleguide#services)
