### ISSUE TITLE
rule `service-name` better have the ability to differ angular.module#factory() regex

### ISSUE THREAD

**Issue by oriSomething** [Gillespie59/eslint-plugin-angular#420]
The reason is, since `factory` doesn't return always an `Object` (unlike `angular.module#service()`).
Sometime `factory` returns value is a function, And since that, I prefer to have two different regexes, because I don't want to have mistakes with services name.

Thanks for your time

**Comment by oriSomething** [comment]
by the way, if you need a help in writing this rule just say. i only need the details

**Comment by Gillespie59** [comment]
Why not creating a specific rule for every kind of service  : service
provider and factory ?

**Comment by oriSomething** [comment]
I don't mind, I think it's preferable

**Comment by oriSomething** [comment]
So before I'm starting to work on this, let's break it the the thing are needed.
- `service-name` will only apply to services
- `isAngularServiceDeclaration` will only apply yo services
- adding `isAngularFactoryDeclaration` and`factory-name` (same options of `service-name`)
- adding `isAngularProviderDeclaration` and`provider-name` (same options of `service-name`)
- adding `isAngularConstantDeclaration` and`constant-name` (same options of `service-name`)
- adding `isAngularValueDeclaration` and `value-name` (same options of `service-name`)
- of course tests for everything

Tell me if I'm good to go

**Comment by Gillespie59** [comment]
sounds good for me. Enjoy ;)

**Comment by oriSomething** [comment]
There is also the consideration that it's breaking changes. Maybe we should add flag to `service-name` for the new behaviour so we will be able to merge it before major release?

**Comment by Gillespie59** [comment]
Yes good idea. You can maybe add a warning message when the service-name is loaded, explaining the next change. Once this PR done, we will merge in the master an publish a version. 
And then, we will publish a major release with the change.

**Comment by oriSomething** [comment]
opened PR #421
