### ISSUE TITLE
A value recipe with an empty array breaks the linter

### ISSUE THREAD

**Issue by dpatti** [Gillespie59/eslint-plugin-angular#425]
If you lint this code:

```js
angular.module('MyModule').value('emptyArray', []);
```

certain rules will break the linter with this:

```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at findFunctionByNode (eslint-plugin-angular/rules/utils/angular-rule.js:202:17)
    at checkCallee (eslint-plugin-angular/rules/utils/angular-rule.js:150:25)
```

I believe the issue is the assumption that the array always has elements:

```js
/**
 * Find the function expression or function declaration by an Angular component callee.
 */
function findFunctionByNode(callExpressionNode, scope) {
    // ...
    if (node.type === 'ArrayExpression') {
        node = node.elements[node.elements.length - 1];
    }
    // ...
}
```

**Comment by Gillespie59** [comment]
Which version of the plugin you use ? 

Because we have an if statement just before this code : 

```javascript
if (!node) {
            return;
        }
```

**Comment by dpatti** [comment]
I'm using the latest. The check there returns `false` because the node _does_ exist, but `node.elements` is `[]`, so when we do

```js
        node = node.elements[node.elements.length - 1];
```

`node` becomes undefined (i.e., `node = [][0]`). It looks like the code expects all arrays in this position to be injections, but either that isn't true for empty arrays, or that isn't true for values.

**Comment by Gillespie59** [comment]
You are right. Do you know which rules throw the error ?

**Comment by dpatti** [comment]
When I was originally setting up the plugin, it felt like it was happening in about a third of the rules, but it was hard to tell because if any one of them threw everything would fail. The stack trace didn't help narrow it down either. After running into several, I just changed the one empty array value in our codebase to `.value('emptyArray', new Array())` so that I didn't have to deal with it.

Taking a look at the source, I want to say it is any rule that requires [`angularRule`](https://github.com/Gillespie59/eslint-plugin-angular/search?q=angularRule).

**Comment by Gillespie59** [comment]
I can reproduce it. Will solve it this evening maybe ;) Thanks
