### ISSUE TITLE
Warning message of the new angular/service-name should run only once

### ISSUE THREAD

**Issue by oriSomething** [Gillespie59/eslint-plugin-angular#431]
<img width="1053" alt="screen shot 2017-01-01 at 12 00 48" src="https://cloud.githubusercontent.com/assets/2685242/21580786/06e98b84-d01a-11e6-8ec7-7b2c0e925109.png">

By the way it breaks WebStore, I'm not sure if it's feature or a bug ;-)

**Comment by Gillespie59** [comment]
Yes I have see the problem. the console.warn is not at the right place. Can you move it before the object returned by the create method ?

**Comment by oriSomething** [comment]
Of course, I've put me as  assignee for that.

**Comment by mateatslc** [comment]
upgraded to `v1.6.2` but this still seems to be broken.
as per https://github.com/Gillespie59/eslint-plugin-angular/pull/448 it got reverted.
