### ISSUE TITLE
timeout-service should fail on $window.setTimeout

### ISSUE THREAD

**Issue by swar30** [Gillespie59/eslint-plugin-angular#434]
Right now timeout-service rule warns on `setTimeout` and on `window.setTimeout` but it does not warn on `$window.setTimeout` which is an unfortunate option as well.

Planning to provide pull request with added support, please let me know if there are any objections

**Comment by swar30** [comment]
@Gillespie59 now that this has been merged to development branch, when will it make it into a release ?
I'm in no hurry as currently planning to have direct dependency on github branch in my repo, but would like to setup reminder of when I can switch to official release.

**Comment by Gillespie59** [comment]
I will publish the new version when this PR is finished : https://github.com/Gillespie59/eslint-plugin-angular/pull/432

**Comment by swar30** [comment]
It looks like it's not going to finish soon, think you can publish without
it?

**Comment by swar30** [comment]
@Gillespie59 any input on this, can we push forward release of new version with #435 ?

**Comment by Gillespie59** [comment]
1.6.2 publish

**Comment by swar30** [comment]
Thanks
