### ISSUE TITLE
module-dependency-order: allow Identifiers

### ISSUE THREAD

**Issue by jrencz** [Gillespie59/eslint-plugin-angular#437]
For projects like https://github.com/AngularClass/NG6-starter where ng dependency names are imported with ES modules the names of ng modules are not string literals.

Non-ES modules example (works now):
```js
angular.module('foo', [
  'bar',
  'baz',
]);
```

ES modules example (should work):
```js
import bar from 'path/to/bar';
import baz from 'path/to/baz';

const fooModule = angular.module('foo', [
  bar,
  baz,
]);

export default homeModule.name;
```

**Comment by graingert** [comment]
I'd like a rule to enforce identifiers.

**Comment by graingert** [comment]
@jrencz what's this blocked on, and can this be configured to only allow identifiers?

**Comment by jrencz** [comment]
I believe rules are about what syntactic thing they enforce and their configs are for what varian of that syntax they enforce. So yes: there should be a way to enforce either literals or identifiers, but IMO it should be one rule.

**Comment by Gillespie59** [comment]
Yes It should be a new rule. Can you create it @graingert or @jrencz ?
