### ISSUE TITLE
Rule `typecheck-object` is failed for simple comparing with 'object'

### ISSUE THREAD

**Issue by Valdermeyder** [Gillespie59/eslint-plugin-angular#444]
Rule `typecheck-object` is failed for simple comparing with 'object' string

```javascript
var variable = 'object';
return variable === 'object'
```

Same issue with other `typecheck-*` rules

**Comment by alfaproject** [comment]
You are not checking for a type in your code

**Comment by Gillespie59** [comment]
I have just added few unit test, and it looks like this issues is already resolved. I can not reproduce the problem

**Comment by Valdermeyder** [comment]
@Gillespie59 are you sure that this is fixed? I still experienced the issue using version 2.2.0. Could you point me to unit test which you have added to fix the issue?
