### ISSUE TITLE
Breaking changes with the latest eslint upgrade

### ISSUE THREAD

**Issue by akanshmurthy** [Gillespie59/eslint-plugin-angular#456]
Eslint 3.18.0 upgrade has changes that negatively affect this plugin.

Specific error encountered: Warning: Syntax error in selector "angular:animation" at position 8: Expected "declaration", "expression", "function", "pattern" or "statement" but "a" found.  Use --force to continue.

**Comment by Gillespie59** [comment]
Related to #454
