### ISSUE TITLE
still too many `angular/service-name` warnings

### ISSUE THREAD

**Issue by mateatslc** [Gillespie59/eslint-plugin-angular#459]
this is to resurrect #431, that is closed although not fixed.

sample output from `v2.0.0`:
![screen shot 2017-03-20 at 11 01 38 am](https://cloud.githubusercontent.com/assets/590577/24095268/9e9dbca0-0d5c-11e7-8f7f-ae51d6796e8f.png)

**Comment by joh-klein** [comment]
I have 4095 lines of "The rule …". This is log spam.

**Comment by Gillespie59** [comment]
I have a publish a fix on the dev branch. Can you test it ?

**Comment by mateatslc** [comment]
with `"eslint-plugin-angular": "Gillespie59/eslint-plugin-angular#development"` in my `package.json` I still see no difference in the output :/

**Comment by Gillespie59** [comment]
Issue finally solved with the 2.2.1
