### ISSUE TITLE
requirejs's require.config hits angular/module-getter rule

### ISSUE THREAD

**Issue by michael-smith-tanium** [Gillespie59/eslint-plugin-angular#474]
Using requirejs's require.config function causes the angular/module-getter rule to get hit. I'm not sure if there is some setting I can use to prevent this or if this is an actual issue.

This boolean check in module-getter.js is causing the issue, though I'm not clear as to what the fix is based on what the intention of this is.

calleeObject.type resolves to `"Identifier"`
utils.isAngularModuleGetter(calleeObject) resolves to `false`

>                    if (!(calleeObject !== undefined && calleeObject.type === 'CallExpression' && utils.isAngularModuleGetter(calleeObject))) {
>                        context.report(node, 'Avoid using a variable and instead use chaining with the getter syntax.');
 >                   }

error  Avoid using a variable and instead use chaining with the getter syntax  angular/module-getter

>    require.config({ 
>       paths: {
>            myDep: 'path/to/myDep'
>        }
>    });

**Comment by Gillespie59** [comment]
Thanks for this issue. A fix has been pushed and will be available with 2.4.1
