### ISSUE TITLE
`oldBehavior` documentation

### ISSUE THREAD

**Issue by blakcap** [Gillespie59/eslint-plugin-angular#480]
I got a warning after I upgraded this plugin:
```
The rule `angular/service-name` will be split up to different rules in the next version. Please read the docs for more information
```
Looking at the docs, I see that the rule has something about setting `oldBehavior` to `false`. However, I have no clue what this is talking about, even after reading the code/issues that reference "oldBehavior". Could some documentation on this and how to migrate to the "new" behavior be added?

Thanks!

**Comment by simison** [comment]
@blakcap would you want to PR docs? :-)

**Comment by Rugile1276** [comment]
Hello @blakcap, have you solved your issue? I get the same problem and cannot understand why..
Help will be really appreciated!
