### ISSUE TITLE
eslint function error

### ISSUE THREAD

**Issue by ashrafmangalore** [Gillespie59/eslint-plugin-angular#489]
Hi, I get error as **Unexpected function expression, Missing function expression name** I am using nodejs
![screenshot from 2017-07-27 12-17-43](https://user-images.githubusercontent.com/28133954/28657763-1836950e-72c6-11e7-8160-c4fc24d2a49c.png)

**Comment by Gillespie59** [comment]
Which rule is root cause of the problem ?

**Comment by ashrafmangalore** [comment]
I resolved it. Thank you
