### ISSUE TITLE
angular/file-name cannot address webpack integration

### ISSUE THREAD

**Issue by dphengsiaroun** [Gillespie59/eslint-plugin-angular#492]
When using Webpack with AngularJS, the code is usually written as follow:  
```
import {myComponent} from 'my-component.component.js'
angular.module('my-module')
    .component('myComponent', myComponent);
```

How to check that the filename (my-component.component.js) is following the John Papa rules while using the eslint-plugin-angular ?

**Comment by Gillespie59** [comment]
you should update the file-name rule, maybe with anotheer option. 
Are you interested by sending a PR ?

**Comment by dphengsiaroun** [comment]
done. You can find the PR.

**Comment by Gillespie59** [comment]
Thanks a lot

**Comment by dphengsiaroun** [comment]
Sorry, i have a use case where the file-name rule crashes. I make a PR to fix that.
Problem is : 

`
if (variable.defs[0].parent.type !== 'ImportDeclaration') {
        return defaultFilename;
    }
`

sometimes variable does not exist, sometimes parent does not exist... So need to make code more secure.

`
 // Check that the definition is an import declaration.
    if (!(variable && variable.defs && variable.defs[0] && variable.defs[0].parent && variable.defs[0].parent.type === 'ImportDeclaration')) {
        return defaultFilename;
    }
`

**Comment by dphengsiaroun** [comment]
The PR is done.
#505

**Comment by Gillespie59** [comment]
Thanks a lot ;)

**Comment by Gillespie59** [comment]
Will publish a new version tomorrow
