### ISSUE TITLE
Move the rule docs to docs/rules

### ISSUE THREAD

**Issue by j-f1** [Gillespie59/eslint-plugin-angular#493]
Currently, the rule docs are stored in the `docs` directory. However, many other ESLint plugins store their rule docs in a `docs/rules` directory, and the ESLint yeoman plugin puts the documentation for a generated rule there by default.

Could you move the rule docs to `docs/rules`?

**Comment by simison** [comment]
@j-f1 would you be interested to PR this change?

**Comment by j-f1** [comment]
Sure!

**Comment by simison** [comment]
@j-f1 note that I'm not a maintainer so I don't know what @Gillespie59 thinks about that change, but PR'ing always encourages _some_ action. ;-)

**Comment by Gillespie59** [comment]
I have just cherry-pick these 2 commits. And will be available in the next release. 
Thanks a lot.

**Comment by Gillespie59** [comment]
I had to do a minor fix. In fact the doc is generated. So if we do not update the script (Cf. c6f5a717342f35ff46c8baecd9284ab63c2ce273 ), the documentation will still be located in the previous folder. 
We need also to update the README.
