### ISSUE TITLE
directive-restrict AE does not work when "angular/function-type" set to 'named'

### ISSUE THREAD

**Issue by mdownes** [Gillespie59/eslint-plugin-angular#494]
This is related to #326 that was closed, and is still an issue even with version 3.0.0

When the following **2** rules are used together, you get the following error:
**Missing directive restriction  angular/directive-restrict**

**Rules**
```
"angular/function-type": [
      "error",
      "named",
      [ "controller", "factory", "service", "directive" ]
    ],
    "angular/directive-restrict": [
      "error",
      {
        "restrict": "AC",
        "explicit": "always"
      }
    ]
```

The example code you need to use is:
```
(function() {
    'use strict';
    angular.module('aaa')
        .directive('myDirective', myDirective);
        
        function myDirective() {
            return {
                restrict: 'A',
                link: function(scope, element, attr) {
                    
                }
            };
        }
})();
```

**The important thing to note is that myDirective is a named function and not an inline function.**
Please  let me know if you need anymore information.

**Comment by simison** [comment]
Would you like to PR at least a test? :-)

**Comment by mrblonde91** [comment]
I agree with @simison

**Comment by quintenp** [comment]
Yes please write proper tests

**Comment by mrblonde91** [comment]
Definitely needs more tests.

**Comment by Gillespie59** [comment]
I am goind to cherry-pick the patch into the dev, and will be available in the nex release ;)
