### ISSUE TITLE
Fix Travis

### ISSUE THREAD

**Issue by simison** [Gillespie59/eslint-plugin-angular#499]
Travis is failing for master and all PR's.

https://travis-ci.org/Gillespie59/eslint-plugin-angular

People are more motivated sending (and working on) PRs when they see builds passing.

**Comment by Gillespie59** [comment]
Duplicate from #483  I think.

**Comment by Gillespie59** [comment]
I am currently working on it :D

**Comment by simison** [comment]
Great! Thanks. :thumbsup:
