### ISSUE TITLE
Run Blocks (Y171)

### ISSUE THREAD

**Issue by Gillespie59** [Gillespie59/eslint-plugin-angular#53]
- Any code that needs to run when an application starts should be declared in a factory, exposed via a function, and injected into the [run block](https://docs.angularjs.org/guide/module#module-loading-dependencies).

    *Why?*: Code directly in a run block can be difficult to test. Placing in a factory makes it easier to abstract and mock.

  ```javascript
  angular
      .module('app')
      .run(runBlock);

    runBlock.$inject = ['authenticator', 'translator'];

    function runBlock(authenticator, translator) {
        authenticator.initialize();
        translator.initialize();
    }
  ```

**Comment by remcohaszing** [comment]
I would like to implement this for the next version.

My initial idea was to check for call expressions which may or may not be member expressions. These call expressions may not take any arguments:

**good**
```js
.run(function(...) {
  kittenService.initialize();
  startup();
})
```

**bad**
```js
.run(function(...) {
  var result = kittenService.initialize();
  startup(result);
})
```

I'm working on a Cordova project, in which a splash screen is used. This allows to use asynchronous setup in which the splash screen is removed as the last part in a promise chain. Should this type of setup in the run function also be accepted?

```js
.run(function(...) {
  kittenService.initialize()
    .then(asyncStartup)
    .then($cordovaSplashscreen.hide);
})
```

What do you think @Gillespie59 @tilmanpotthof ?

**Comment by remcohaszing** [comment]
Never mind about the asynchronous setup. This is a very specific use case and even *if* this is the case, the setup can still be delegated to a service.
