### ISSUE TITLE
Naming Guidelines (Y120) 

### ISSUE THREAD

**Issue by Gillespie59** [Gillespie59/eslint-plugin-angular#56]
- Use consistent names for all components following a pattern that describes the component's feature then (optionally) its type. My recommended pattern is `feature.type.js`. There are 2 names for most assets:
    * the file name (`avengers.controller.js`)
    * the registered component name with Angular (`AvengersController`)

    *Why?*: Naming conventions help provide a consistent way to find content at a glance. Consistency within the project is vital. Consistency with a team is important. Consistency across a company provides tremendous efficiency.

    *Why?*: The naming conventions should simply help you find your code faster and make it easier to understand.

**Comment by tilmanpotthof** [comment]
+1

**Comment by tilmanpotthof** [comment]
Hi, I'm working on a solution.

https://github.com/tilmanpotthof/eslint-plugin-angular/tree/issue-56/Naming-Guidelines-Y120

So far I have a `typeSuffix` option to specify if and how the component type should be defined. The example in the issue does not match completely my approach, but I will fix that.

**Comment by Gillespie59** [comment]
Thanks @tilmanpotthof . I will have a look to your code asap. ;)

**Comment by tilmanpotthof** [comment]
@Gillespie59 Thanks!

So far I added no documentation, as the feature is WiP but here an overview for the options.

`typeSeparator` - 'dot' | 'dash' | 'underscore'
`ignoreTypeSuffix` - true | false
`nameStyle` - 'dot' | 'dash' | 'underscore'

Valid examples for `app.controller('avangersController')`

avangersController.js - `{}`
avangersController.controller.js - `{typeSeparator: 'dot'}`
avangers.js - `{ignoreTypeSuffix: true}`
avangers.controller.js - `{typeSeparator: 'dot', ignoreTypeSuffix: true}`

Valid examples for `app.service('avangersApi')`

avangersApi.js - `{}`
avangersApi.service.js - `{typeSeparator: 'dot'}`
avangersApi-service.js - `{typeSeparator: 'dash'}`
avangersApi-service.js - `{typeSeparator: 'dash', ignoreTypeSuffix: true}`
avangers-api.service.js - `{nameStyle: 'dash', typeSeparator: 'dot'}`

Valid examples for `app.factory('avangersService')`

avangersService.js - `{}`
avangersService-service.js - `{typeSeparator: 'dash'}`
avangers-service.js - `{typeSeparator: 'dash', ignoreTypeSuffix: true}`
