### ISSUE TITLE
4 rules not found

### ISSUE THREAD

**Issue by johnpapa** [Gillespie59/eslint-plugin-angular#61]
I was able to disable 4 rules and got it to work. These 4 cause errors saying rule not found:

- ng_interval_service
- ng_service_name
- ng_timeout_service
- ng_window_service

Not sure why they are not working.

**Comment by Gillespie59** [comment]
You have this error with the default configuration ? in your local one ? 

If it is in your local configuration, it looks like, you have to prefix all rules with the name of the plugin : 

```
"angular/ng_controller_name": 2,
		"angular/ng_directive_name": 0,
		"angular/ng_empty_controller": 0,
		"angular/ng_filter_name": 0,
		"angular/ng_module_name": 0,
		"angular/ng_service_name": 0,
		"angular/ng_timeout_service": 2,
		"angular/ng_typecheck_array": 2,
		"angular/ng_typecheck_boolean": 2,
		"angular/ng_typecheck_date": 2,
		"angular/ng_typecheck_function": 2,
		"angular/ng_typecheck_number": 2,
		"angular/ng_typecheck_object": 2,
		"angular/ng_typecheck_regexp": 2,
		"angular/ng_typecheck_string": 2,
		"angular/ng_window_service": 2
```

Will investigate the ESLint code today ;)

**Comment by johnpapa** [comment]
Adding these seemed to make the error go away. These are in my `./.eslintrc` file.

**Comment by Gillespie59** [comment]
perfect, I will update the README.md with this trick. 

FYI, here is the code in ESLint : 

{code}
exports.import = function (pluginRules, pluginName) {
    Object.keys(pluginRules).forEach(function (ruleId) {
        var qualifiedRuleId = pluginName + "/" + ruleId,
            rule = pluginRules[ruleId];

        define(qualifiedRuleId, rule);
    });
};
{code}

So all rules have to be prefixed by the plugin name.

**Comment by johnpapa** [comment]
sweet. can you update npm with the ng strict di fix you made too? i'll call this out in the ngConf presentation tomorrow and see if others can help contribute.

**Comment by Gillespie59** [comment]
Yep I will do it ;)
We are lucky with the time difference ;) (France vs USA)
