### ISSUE TITLE
ng_controller_name suffix option

### ISSUE THREAD

**Issue by dustinspecker** [Gillespie59/eslint-plugin-angular#68]
Currently, the ng_controller_name validates a prefix, but the rule refers to John Papa's use of a `Controller` suffix. Should the rule be validating prefixes or suffixes? If it's intended to validate prefixes, it'd be awesome to see another rule for suffix. I wouldn't mind working on this feature and learning how ESLint works.

Thanks for making all of these rules!

**Comment by Gillespie59** [comment]
Hi, 

You can also specify a Regexp. For example, the default value for this rule is : /[A-Z].*Controller$/ : the name should start with an uppercase, and finish with 'Controller'

**Comment by dustinspecker** [comment]
Thank you. Is there a way to provide a RegExp in a JSON formatted .eslintrc? If not, I can make a PR.
