### ISSUE TITLE
npm old version package

### ISSUE THREAD

**Issue by seonetartem** [Gillespie59/eslint-plugin-angular#76]
2015.03.14
after 
npm install --save-dev eslint-plugin-angular
i get old version rules:

module.exports = function(context) {

    'use strict';

    var utils = require('./utils/utils');

    return {

        'CallExpression': function(node) {

            var prefix = context.options[0];

            if(prefix === undefined) {
                return;
            }

            var callee = node.callee;
            if (callee.type === 'MemberExpression' && callee.property.name === 'controller') {
                var name = node.arguments[0].value;

               if(name !== undefined && !utils.isRegexp(prefix) && !(name.indexOf(prefix) === 0)){
                    context.report(node, 'The {{controller}} controller should be prefixed by {{prefix}}', {
                        controller: name,
                        prefix: prefix
                    });
                } else if(utils.isRegexp(prefix) && !prefix.test(name)){
                    context.report(node, 'The {{controller}} controller should follow this pattern: {{prefix}}', {
                        controller: name,
                        prefix: prefix.toString()
                   });
                }

            }
        }
    };

};

pls. update package

**Comment by Gillespie59** [comment]
Which version do you use ? 0.0.6 ? That's maybe normal you do not have the latest version. We do not publish a new version on NPM after each commit.
If you want the newest version, you can install the dep via the git URL.

**Comment by seonetartem** [comment]
i use v0.0.6
and try change default prefix "Controller" => "Ctrl"
....
.eslintrc
...
"rules": {
  "angular/ng_controller_name": [2, "/[A-Z].*Ctrl$/"]
}
......

this version plugin 
var prefix = context.options[0];

prefix type "string" and utils.isRegexp(prefix) all time return false

**Comment by Gillespie59** [comment]
This issue has been solved for the future 0.0.7 release : https://github.com/Gillespie59/eslint-plugin-angular/pull/71
