### ISSUE TITLE
Can't load the eslint-plugin-angular from Grunt using grunt-eslint

### ISSUE THREAD

**Issue by antonioaguilar** [Gillespie59/eslint-plugin-angular#85]
Hi, 

I'm trying to integrate the eslint-plugin-angular as part of my Grunt build system but I can't seem to be able to load the plugin within .eslintrc (json format). I'm using the following node_module dependencies installed locally:

  "devDependencies": {
    "eslint": "^0.16.1",
    "eslint-plugin-angular": "^0.0.7",
    "grunt": "^0.4.5",
    "grunt-eslint": "^7.0.1"
  }

and this is my .eslintrc file:

  {
    "plugins": ["angular"],
    "rules": {
//    "angular/ng_controller_name": [1, " my controller pattern "],
    "quotes": [1, "single"]
    },
    "globals": {
    "angular": true
    }
  }

this is my grunt task:

    eslint: {
      options: {
        /* Available formats: stylish, compact, checkstyle, junit,  */
        format: 'stylish'
      },
      target: ['src/app/**/*.js', '!src/app/**/*.spec.js', '!src/app/**/*.e2e.js']
    },

when I do a "grunt eslint" I get the following error:

Running "eslint:target" (eslint) task
Warning: Cannot read property 'object' of undefined Use --force to continue.

Aborted due to warnings.

Any ideas on what could be causing this error? I tested the same configuration changing the "angular" plugin to the "require" (eslint-plugin-require) and it works without problems. 

I'm trying to find out if this is an issue with grunt-eslint or your plugin. 

thanks, 

Antonio.

**Comment by Gillespie59** [comment]
Hi Antonio

Very strange issue. Normally the plugin works quiet well with the the grunt integration.

Is it possible to have more logs? In order to understand where the problem come from. 

Can you check that the plugin has been downloaded in your node_modules folder?

Manu

**Comment by antonioaguilar** [comment]
Hi Manu, 
Thanks for the fast answer. Yes. The plugin is downloaded and installed in my local node_modules folder. I kept experimenting last night and I downgraded the eslint-plugin-angular to version "0.0.6" and it all worked fine. 

Here are some logs when running Grunt with eslint-plugin-angular version "0.0.7":

$ grunt --debug --stack eslint
Running "eslint:target" (eslint) task
[D] Task source: /Users/antagu/repos/ua-dev/release/ash/clients/browser/node_modules/grunt-eslint/tasks/eslint.js
Warning: Cannot read property 'object' of undefined Use --force to continue.
TypeError: Cannot read property 'object' of undefined
    at getCallingIdentifier (/Users/antagu/repos/ua-dev/release/ash/clients/browser/node_modules/eslint-plugin-angular/rules/utils/utils.js:9:50)
    at Object.module.exports.isUIRouterStateDefinition (/Users/antagu/repos/ua-dev/release/ash/clients/browser/node_modules/eslint-plugin-angular/rules/utils/utils.js:103:22)
    at EventEmitter.CallExpression (/Users/antagu/repos/ua-dev/release/ash/clients/browser/node_modules/eslint-plugin-angular/rules/ng_controller_as_route.js:37:30)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.enter (/Users/antagu/repos/ua-dev/release/ash/clients/browser/node_modules/eslint/lib/eslint.js:735:25)
    at Controller.__execute (/Users/antagu/repos/ua-dev/release/ash/clients/browser/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/antagu/repos/ua-dev/release/ash/clients/browser/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/antagu/repos/ua-dev/release/ash/clients/browser/node_modules/eslint/lib/eslint.js:728:24)
    at processFile (/Users/antagu/repos/ua-dev/release/ash/clients/browser/node_modules/eslint/lib/cli-engine.js:193:27)
    at /Users/antagu/repos/ua-dev/release/ash/clients/browser/node_modules/eslint/lib/cli-engine.js:293:26
    at walk (/Users/antagu/repos/ua-dev/release/ash/clients/browser/node_modules/eslint/lib/util/traverse.js:81:9)

Aborted due to warnings.


Execution Time (2015-04-01 08:46:32 UTC)
eslint:target  796ms

**Comment by Gillespie59** [comment]
It looks like the problem come from the ng_controller_as_route rule. Does your KS code available somewhere ? In order to get file that give this issue. Thanks

**Comment by Gillespie59** [comment]
*your JS sorry

**Comment by antonioaguilar** [comment]
I can't share the JS code because I'm using this internally in a company. You are right, the problem is in ng_controller_as_route rule. When I disable the rule:
{
  "plugins" : ["angular"],
  "rules": {
    "angular/ng_controller_as_route": 0
  }
}
the plugin runs fine.

**Comment by antonioaguilar** [comment]
Hi Manu,
I found that the file that was causing the ng_controller_as_route error was actually a plain javascript SDK file without any angular code. My grunt build parser picked up the file, I added /* eslint-disable */ and /* eslint-enable */ but the file somehow linted. So, how does your plugin behave when you give it a plain javascript file without any angular code and run eslint?
I'm going to keep testing in the next couple days,
A.

**Comment by jbalboni** [comment]
@antonioaguilar Does the file it's breaking on have any code that has a property name of 'state'? That rule looks for a 'state' property and then tries to find the calling identifier and check that it's called '$stateProvider'. It looks like it's breaking after find a 'state' property.

I would be useful to just have a snippet where 'state' is used.

**Comment by antonioaguilar** [comment]
@jbalboni I tracked the bug to this function (see code snippet below). State is defined as a variable. Renaming this variable to something else makes the rule pass. 

```
function parseNotification(notification) {
  var type = notification.notificationType;
  var changeType = notification.notificationChangeType;
  var state = _this.interactionState[notification.newValue.currentState];
  if (typeof updateNotification[type][changeType] === 'function') {
    updateNotification[type][changeType](notification.newValue);
  } else {
    updateNotification[type][changeType][state](notification.newValue);
  }
}
```

**Comment by jbalboni** [comment]
Thanks @antonioaguilar

**Comment by Gillespie59** [comment]
Should be OK now thanks to this PR. thanks both of you !!
