### ISSUE TITLE
Make angular object list configurable for ng_no_services

### ISSUE THREAD

**Issue by grabus** [Gillespie59/eslint-plugin-angular#88]
There is a hardcoded list in the [ng_no_services](https://github.com/Gillespie59/eslint-plugin-angular/blob/master/rules/ng_no_services.js#L7):
```js
var angularObjectList = ['controller', 'filter', 'directive'];
```
But I want to add 'factory' to the list for my project.
What do you think about making this list configurable?

**Comment by Gillespie59** [comment]
Perfect for me. Good idea. You want to contribute to this enhancement?

**Comment by grabus** [comment]
Yes, I'd like to try realize it in the weekend.
